/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.Test;

/**
 * JUnit 5 can be touchy if you don't set it up correctly
 */
public class JUnit5SanityCheck {

    @Test
    public void testJUnit5ContextLoads() {
    }
}
